services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=sk-
    volumes:
      - ./app:/app/app
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE